### ISSUE TITLE
System.IO error on compiling the code

### ISSUE THREAD

**Issue by KKacer** [excubo-ag/Blazor.LazyStyleSheet#1]
Had one issue compiling the source code,
Basically not sure if it is a bug or anything else on MSBuild, but .targets files never triggered unless we import them manually. And when I import the ".targets" file I get this error:

`Error	MSB4184	The expression "[System.IO.Path]::GetDirectoryName('')" cannot be evaluated. The path is not of a legal form.`

You can see this video, for everything be clarified on it:

https://1drv.ms/v/s!AlScPmE9PLAKgSxKUQ_XBmhnZi0d?e=6mQnHy

**Comment by stefanloerwald** [comment]
Hi @KKacer,


the `targets` file is not supposed to be executed within the LazyStyleSheet project. It only has effect on the projects that include LazyStyleSheet. Hence, including it in the csproj file is not necessary.

Your issue with the empty `CurrentFile` might be solvable by adding ` Condition=" '$(CurrentFile)' != '' "` to the target `<Target Name="InjectOneStyleSheetService" Condition=" '$(CurrentFile)' != '' ">`. Could you please try that and report back?

BR
Stefan

**Comment by KKacer** [comment]
Update:
Solved the problem in the main project, will check it in the target later.

**Comment by KKacer** [comment]
Solved the problem in the main project, will check it in the target later.

**Comment by stefanloerwald** [comment]
Fixed in version 2.0.8 with commit [b1ef52b](https://github.com/excubo-ag/Blazor.LazyStyleSheet/commit/b1ef52bdc3094df6bea36ed757e4ae0671fdaa64). Thanks for reporting!
