### ISSUE TITLE
2 Errors at the compile time in a more complex scenario

### ISSUE THREAD

**Issue by KKacer** [excubo-ag/Blazor.LazyStyleSheet#2]
I get these 2 errors in my current yet more complicated setup.
I moved a library master file, let's call it "_ProSetAll.scss" including several inner libraries. (compilation in the library is off)
It is based on your Lib/Consumer approach with nugets, with 1 extra project in between: `LibCommon > LibWeb > Main App`, all using the LazyCss and the all the previous projects in the given order.
Here I am extending the functionalities of the current tools and may find some related bugs also.
Guess if you check the 2 attached images you may get the current situation. 

**Error1:**
`Error		
File to import not found or unreadable: ..ProSet_ProSetAll.scss.	
BlazorApp	D:\Addr\7\BlazorApp\EXEC	1	`

**Error 2:**
`Error	MSB3073	The command "webcompiler -r wwwroot" exited with code 1.`

**Site.Scss:**
`@import "..\ProSet\ProSetAll";`
(It is right there)

**Screenshots:**
https://postimg.cc/JHHh7fxR
https://postimg.cc/bd4JVvYr

My current guesses about the issues could be:
1. the order of the target sections, 
2. The main LazyCss build targets file should be edited to include my library, and handle the situation better.
3. WebCompiler is crashing cause of a complexity on the various imports and their paths.
4. I don't know how well I be able to use messages to debug and find the exact cause of the error to fix it.

I know that I am not still done with it, though the complete package seems to be in a good state. (still will try my best to resolve it)

**Comment by stefanloerwald** [comment]
This does not seem to be an issue with either LazyStyleSheet or Webcompiler, as this occurs within the compilation of a sass file. 

However, the root cause of most likely the usage of the path separator \ instead of /.

**Comment by KKacer** [comment]
Oh! you were right,
So, the reason was much simpler than what I thought.
I don't know why I used slashes there. Solved.
