### ISSUE TITLE
About Component Styles

### ISSUE THREAD

**Issue by KKacer** [excubo-ag/Blazor.LazyStyleSheet#3]
There are 2 issues/question about the Components styles:

https://postimg.cc/FfgJy7Yd
https://postimg.cc/0rL2N9NL

1.  Seems the file nesting doesn't work anymore (about the components styles, should we do anything extra?
2. The component_library folder only contains "ComponentWithUserDefinedColor.razor.scss"
and not the razor file, not sure if I remember correctly, cause it took a while that I was concentrated on other MSBuild topics and not on the component styles.
If I remember correctly I think it is supposed to have both .razor and .razor.scss there, right?

**Here I am using your latest releases untouched. This is the **comopnent_library** example.** In my previous examples that I was working with this library and had a focus on the main architecture also the result was the same on the components' styles side. 
Not sure have some doubt that it may be even related to the latest update I made to VS from 
16.5.4 to 16.6. Guess in my earlier trials the result was different, though now in every fresh project also the result is the same.

_Visual Studio 16.6_

---
**Update:**
Seems the File-nesting issue '#1' is currently an ongoing development:
https://github.com/dotnet/project-system/issues/5722

Think this will be the last issue I have currently with your great tool.
Thanks for the help,
Regards,
Kasra

**Comment by stefanloerwald** [comment]
Hi Kasra,

regarding 1) component styles:
This is a VS feature completely unrelated to LazyStyleSheet. As far as I know, file nesting only works in web projects, although I wish it would work anywhere.

regarding 2) output folder:
The only files that should be in a `wwwroot` folder are static assets. razor files do not belong in there (otherwise people could download your raw source code). So this is not a bug.

BR
Stefan

**Comment by KKacer** [comment]
Aha, so that is working as expected, wanted to be assure whether to expect a change in the components directory or not, and that is fine, you are right about the components.
Was mostly a question/doubt not a bug.
Thanks.
